# Generated by Django 5.2.4 on 2025-07-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Digitalapp', '0001_initial'),
        ('Traditionalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Traditionalapp.customerlist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Digitalapp.productlist')),
            ],
        ),
    ]
