# Generated by Django 5.2.4 on 2025-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
